import type { WorkOrder } from "./workOrders.types";

export const workOrders: WorkOrder[] = [
  {
    id: "WO-1042",
    partNumber: "SRV-8821-A",
    partName: "Upper Actuator Bracket",
    customerProgram: "Aquila",
    material: "7075 Aluminum",
    quantity: 24,
    completedQuantity: 18,
    machine: "DMG Mori DMU 50",
    stage: "inspection",
    priority: "high",
    dueDate: "2026-07-25",
  },
  {
    id: "WO-1043",
    partNumber: "SRV-1904-C",
    partName: "Guidance Housing",
    customerProgram: "Orion",
    material: "Titanium",
    quantity: 12,
    completedQuantity: 5,
    machine: "Haas VF-2SS",
    stage: "machining",
    priority: "critical",
    dueDate: "2026-07-24",
  },
  {
    id: "WO-1044",
    partNumber: "SRV-5510-B",
    partName: "Sensor Mount",
    customerProgram: "Aquila",
    material: "6061 Aluminum",
    quantity: 40,
    completedQuantity: 0,
    machine: " ",
    stage: "ready",
    priority: "normal",
    dueDate: "2026-07-29",
  },
  {
    id: "WO-1045",
    partNumber: "SRV-7712-D",
    partName: "Valve Body",
    customerProgram: "Helios",
    material: "Stainless Steel",
    quantity: 16,
    completedQuantity: 8,
    machine: "Mazak VARIAXIS",
    stage: "blocked",
    priority: "high",
    dueDate: "2026-07-26",
    blockedReason: "Awaiting replacement cutting tool",
  },
  {
    id: "WO-1046",
    partNumber: "SRV-3018-A",
    partName: "Control Arm",
    customerProgram: "Orion",
    material: "Inconel",
    quantity: 8,
    completedQuantity: 8,
    machine: "Okuma MU-5000V",
    stage: "complete",
    priority: "normal",
    dueDate: "2026-07-23",
  },
  {
    id: "WO-1047",
    partNumber: "SRV-6244-F",
    partName: "Avionics Tray",
    customerProgram: "Vega",
    material: "6061 Aluminum",
    quantity: 30,
    completedQuantity: 0,
    machine: " ",
    stage: "cam",
    priority: "low",
    dueDate: "2026-08-01",
  },
];